### ISSUE TITLE
Package distribution

### ISSUE THREAD

**Issue by florianhartig** [biometry/RLPJ#1]
Hey guys, we should find another solution for the source packages, it's not good style to have this in the repo. 

First of all, I assume the reason why you do this is that otherwise the vignette doesn't build properly? Because if that wasn't a problem, you could install directly from github http://www.inside-r.org/packages/cran/devtools/docs/install_github

Secondly, the better way to distribute binaries is to do proper releases via https://help.github.com/articles/creating-releases/ - I think you can upload binaries there. We should then link to the release on the main page.

**Comment by florianhartig** [comment]
btw, I would start the release numbering now with 0.1, i.e. 0.1 is our initial release of the package.

Small updates should be 0.1.0.1 ... etc.

Larger updates should be 0.1.1 ...

**Comment by Rasilgon** [comment]
OK. I will remove from the repo and check the other options. 

Currently there is no vignette. We just cannot use any function that requires to have the model.
I can however create a vignette based on thte old one (gettingstarted) and remove outdated parts.

The vignette should then pose no problem. If so, we can use the first option: installing_github.
I do not know how this works. I have tried but I get an error (see below). I would appreciate if you give a hint here.
`devtools::install_github("biometry/RLPJ", ref = "master")`
`Downloading GitHub repo biometry/RLPJ@master from URL https://api.github.com/repos/biometry/RLPJ/zipball/master`
`Error: Does not appear to be an R package (no DESCRIPTION)`

**Comment by Rasilgon** [comment]
I set version to 0.1
What about license?

**Comment by florianhartig** [comment]
for the devtools, you have to provide the exact location of the package, i.e.

devtools::install_github("biometry/RLPJ/Rlpj", ref = "master")

I just tried it, it works fine. I would suggest that we let people install the development version this way, then we don't have to tag releases all the time

**Comment by Rasilgon** [comment]
I created a vignette and there is no problem when installing form github. I will complete the installation instructions.
