### ISSUE TITLE
Provided more options in template cf

### ISSUE THREAD

**Issue by Rasilgon** [biometry/RLPJ#13]
Up to now, users can pass path to the nc input files , but not the name of the variable:

```
param "file_temp"     (str "path_to_temp.nc")
param "variable_temp" (str "temp")
```

However, the variable_temp values must be also modified because it determined by nc file.

We could either provide more options on modifying this or let users pass the right template.
The first  implies changes in code, the second does not.

**Comment by mauriziobagnara** [comment]
make variable names user defined

**Comment by Rasilgon** [comment]
This was solved. I forgot to close it.
