### ISSUE TITLE
Model outputs

### ISSUE THREAD

**Issue by florianhartig** [biometry/RLPJ#16]
Maurizio, can you tell me again which outputs you want for which temporal resolutions? If you have already an idea about how to best organize this you can also add it here (note that files could get quite large).

**Comment by mauriziobagnara** [comment]
Ideally, fluxes at hourly or daily resolution (GPP, NEE, NPP, ET and so on), depending on how they are calculated internally, plus diameter distributions yearly. To organize them, I would try to keep the same structure of yearly outputs for dbh distribution, and similar for the hourly/daily new fluxes if it's feasible.
