### ISSUE TITLE
Add more settings for template creation

### ISSUE THREAD

**Issue by mauriziobagnara** [biometry/RLPJ#17]
Ideally, it should be possible to edit/specify all the following settings/options directly from R:

`!///////////////////////////////////////////////////////////////////////////////////////
!// RUN PARAMETERS AND OPTIONS
!

vegmode "cohort"      ! "cohort", "individual" or "population"
nyear_spinup 500      ! number of years to spin up the simulation for
ifcalcsla 1           ! whether ctonto calculate SLA from leaf longevity
                      ! (PFT-specific value can be specified in this file instead)
ifcalccton 1          ! whether to calculate leaf C:N min from leaf longevity
                      ! (PFT-specific value can be specified in this file instead)
iffire 1              ! whether to implement fire (1) or not (0)
npatch 25             ! number of replicate patches to simulate
patcharea 10000        ! patch area (m2)
estinterval 1         ! years between establishment events in cohort mode
ifdisturb 1           ! whether generic patch-destroying disturbances enabled
distinterval 200      ! average return time for generic patch-destroying disturbances
                      ! Hickler et al. (2011) used 200
ifbgestab 1           ! whether background establishment enabled
ifsme 1               ! whether spatial mass effect enabled
ifstochestab 1        ! whether establishment stochastic
ifstochmort 1         ! whether mortality stochastic
ifcdebt 1             ! whether to allow vegetation C storage (1) or not (0)
wateruptake "rootdist"! "wcont", "rootdist", "smart" or "speciesspecific",
                      ! see documentation for water_uptake()

!///////////////////////////////////////////////////////////////////////////////
! PROCESS SETTINGS SPECIFIC TO NITROGEN
!///////////////////////////////////////////////////////////////////////////////

ifcentury 1             ! whether to use CENTURY SOM dynamics (mandatory for N cycling)
ifnlim 0                ! whether plant growth limited by available N
freenyears 100          ! number of years to spin up without N limitation (needed to build up a N pool)
nfix_a 0.234            ! first term in N fixation eqn (Conservative 0.102, Central 0.234, Upper 0.367)
nfix_b -0.172           ! second term in N fixation eqn (Conservative 0.524, Central -0.172, Upper -0.754)
nrelocfrac 0.5          ! fraction of N retranslocated prior to leaf and root shedding

!///////////////////////////////////////////////////////////////////////////////
! SERIALIZATION SETTINGS
!///////////////////////////////////////////////////////////////////////////////
!state_year             ! year to save/start state file (no setting = after spinup)
restart 0               ! wheter to start from a state file
save_state 0            ! wheter to save a state file
state_path ""           ! directory to put state files in

ifsmoothgreffmort 1             ! whether to vary mort_greff smoothly with growth efficiency (1)
                                ! or to use the standard step-function (0)
                                ! greff_min values below calibrated for the smooth (1) option
ifdroughtlimitedestab 1         ! whether establishment is limited by growing season drought
ifrainonwetdaysonly 1           ! whether to rain on wet days only (1), or to rain a bit every day (0)
ifbvoc 0              ! whether to include BVOC calculations (1) or not (0)

!!!!!!!!!!!! landcover parameters !!!!!!!!!!!!!!

run_landcover 0        ! whether to use (and change) landcover fractions (1) or not (0)

run_urban 0       ! whether to simulate barren land (1) or not (0)
run_crop 1        ! whether to simulate crop vegetation (1) or not (0)
run_forest 0          ! whether to simulate managed forest (1) or not (0)
run_pasture 0         ! whether to simulate pasture (1) or not (0)
run_natural 1         ! whether to simulate natural vegetation (1) or not (0)
run_peatland 1        ! whether to simulate peatland (1) or not (0)

lcfrac_fixed 0          ! use landcover fractions (%) below (1) or read from input file (0)
lc_fixed_urban 0    ! URBAN
lc_fixed_cropland 50    ! CROPLAND
lc_fixed_pasture 0      ! PASTURE
lc_fixed_forest 0       ! FOREST
lc_fixed_natural 25     ! NATURAL
lc_fixed_peatland 25    ! PEATLAND
equal_landcover_area 0  ! divide gridcell into equal active landcover fractions`

As always, default values should be used if not specified otherwise by the user.

**Comment by Rasilgon** [comment]
This is implemented already. What is new to be solved is #18
