### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by florianhartig** [biometry/RLPJ#2]
Ramiro, if we have sorted out the distribution issue https://github.com/biometry/RLPJ/issues/1, can you
- Create some basic install instructions in the readme.md file
- Create a project website in settings -> automatic page generator, which describes the package in a few words and also includes the install instructions - on the long term, people should be directed to the website and not to the code folder

**Comment by Rasilgon** [comment]
I have edited the Readme and included the installation instructions.

I do not have access / rights to modify the settings of this repository. The settings tab does not show up for me.

**Comment by mauriziobagnara** [comment]
remember to update install instructions for each new release
