### ISSUE TITLE
Option to save outputs

### ISSUE THREAD

**Issue by Rasilgon** [biometry/RLPJ#20]
Include an option that allow users whether to save the outputs as RData or not.
Currently, it always saves them in the _runInfo_ folder.

**Comment by mauriziobagnara** [comment]
check. If done, close issue.

**Comment by Rasilgon** [comment]
There is an option to save the outputs as RData (settings$save = T). Default is true, so the outputs will be saved.

**Comment by Rasilgon** [comment]
Besides, I created a new function **getRunInfo** that allows to reload from the runInfoDir folder all data or solely the parameterList as a matrix. Additionally, could retrieve the parameter list from the "result" (ouput of runLPJ" parallel). I had to this several times in my own code and I thought that it will be useful to have it the package.
