### ISSUE TITLE
plotLPJData: plot from parallel output

### ISSUE THREAD

**Issue by Rasilgon** [biometry/RLPJ#21]
Currently plotLPJData allows to plot the output of runLPJ ( a LPJData class object)
If runLPJ was used for a parallel call, the plot function must be call for each object in the returned output (output is a list holding LPJData objects).

It might be interesting  to allow passing the entire list to plotLPJData and that the function plots all runs for each output type : 
- in a plot panel and/or
- in same plot

This will be helpful to quickly compare runs.

**Comment by mauriziobagnara** [comment]
good point, but not priority
