### ISSUE TITLE
RunLPJ in cru mode returns empty outputs

### ISSUE THREAD

**Issue by Rasilgon** [biometry/RLPJ#26]
When running the LPJ-GUESS with the cru template, the model outputs are empty. No error is returned by LPJ-GUESS.

**Comment by Rasilgon** [comment]
I found a bug in reading and writing the cru template.

When the runLPJwrapper replaces path_to_cru as it does now,  it will do so not only in file_cru but also file_cru_misc. The _gsub_ pattern should be modified.

- param "file_cru"      (str "path_to_cru")
- param "file_cru_misc" (str "path_to_cru_misc")

However, even I correct the error in the template the problem persists.

Can anyone run the model with cru template and obtaining the outputs?
Could the input data be the cause?

**Comment by mauriziobagnara** [comment]
I ran the model from terminal with its original .ins files, still returns empty outputs. This does not seem to be a package problem...

**Comment by mauriziobagnara** [comment]
I'll run the model with the gridlist file supposed to work with the cru climate input, to see if this works.

**Comment by florianhartig** [comment]
Is this solved?

**Comment by mauriziobagnara** [comment]
This is a bug in the original LPJ-GUESS code: the model returns empty outputs (only sometimes) but it is completely unrelated to the package.
