### ISSUE TITLE
LPJ individual mode

### ISSUE THREAD

**Issue by mauriziobagnara** [biometry/RLPJ#27]
I tried to run Rlpj in "individual" mode (one of the design option), the model crashes without any error message in the log file. Running from terminal, the messages look like this:

```
[LPJ-GUESS  Fri Jan 27 11:27:21 2017]



--------------------------------------------------
LPJ-GUESS cohort mode - European species
--------------------------------------------------

Commencing simulation for gridcell at (10.454,51.0802)
Description: Hainich
Using soil code and Nitrogen deposition for (10.0,51.0)
Segmentation fault: 11
```

It seems to be a problem with netcdf input files, probably they need to have a different structure. Have we ever tested it? Ramiro?

**Comment by florianhartig** [comment]
Is this now solved or not?

**Comment by mauriziobagnara** [comment]
runs fine for me
