### ISSUE TITLE
update default parameter values

### ISSUE THREAD

**Issue by mauriziobagnara** [biometry/RLPJ#28]
Insert csv parameter file in the package and use it in .Rmd files for the Rlpj paper.

**Comment by Rasilgon** [comment]
The calibration parameters are in the package. I put the file in the extdata folder and it can be accessed as follows:

    LPJparameters <- system.file("extdata", "LPJParameters_calibrate.csv", package = "Rlpj")
    LPJparameters <- read.csv(LPJparameters,  sep = ",")
