### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Algernonthanks** [biometry/RLPJ#31]
what is the "file.cru.misc " , What does it mean? and

**Comment by florianhartig** [comment]
The runLPJ help says "a character string providing the absolute path to the cru input file" - does that help?

**Comment by mauriziobagnara** [comment]
The "cru" files are input files required by LPJ-GUESS to run. They are provided by the developer with the LPJ-GUESS source code, usually in the "crudata" folder. Specifically, 3 files from the "crudata" folder are required: file.cru (named something like "cru_1901_2006.bin"), file.cru.misc (named something  like "cru_1901_2006misc.bin") and file.ndep (named something like "GlobalNitrogenDeposition.bin") - Hope it helps!
