### ISSUE TITLE
Commented code in the vignette

### ISSUE THREAD

**Issue by florianhartig** [biometry/RLPJ#32]
In the vignette, there are various code places that are commented out, to avoid that the model is run, such as

```
# and lets check what it has been written in the template
# if no value was provided for the parameters, they have been set to default values
template [c(156:166)]

# Next step is to call the model
# but we skip it
# runLPJ(mainDir, runDir, "global_cru.ins")
```

This is not good style - you should solve this via an extra chunk, setting eval = F, which suppresses the code execution

**Comment by Rasilgon** [comment]
You are right, this I can do.

**Comment by mauriziobagnara** [comment]
Solved
