### ISSUE TITLE
CRAN Checks

### ISSUE THREAD

**Issue by florianhartig** [biometry/RLPJ#33]
I just ran the CRAN checks over the current main branch, and there was one error in the unit tests, and several notes

**Comment by florianhartig** [comment]
OK, the errors were because of the missing binaries. I changed the Travis checks now, this is for the moment resolved.

Warnings and notes should still be resolved, these are usually meaningful, in the sense that something is not coded properly

**Comment by mauriziobagnara** [comment]
This is solved now, right?

**Comment by florianhartig** [comment]
yes
