### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by Rasilgon** [biometry/RLPJ#37]
The package name will be changed to rLPJGUESS.

**Comment by Rasilgon** [comment]
We are currently on version v1.0.1. How should  the change affect the version number?

**Comment by Rasilgon** [comment]
S4 classes of the package and functions are named runLPJ or LPJData. Should everything be renamed to be LPJGUESS instead of LPJ? I assume that here it is not necessary to change LPJ by LPJGUESS, but I'd appreciate if you confirm it.

**Comment by florianhartig** [comment]
best practice for the version number would be to a) make a branch for every suite of changes b) increase the version number if the branch is merged in via a pull request.

If that is not done, I would simply count up to 1.1

**Comment by florianhartig** [comment]
About the S4 classes - yes, I would keep the old names, changing this would also break compatibility for reading in old simulations with the new package version
