### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by Rasilgon** [biometry/RLPJ#38]
The package license we previously had include a file, LICENSE, that has further specifications to GPL-3. Should be kept or deleted?

> The Rlpj package is licenced under GPL-3, with the following additions (permitted under section 7 of the GPL-3):
> 
> 1) Attribution: any derivatives of this work must prominently acknowledge the original authors (either the authors of the entire package, or, if only a particular function is used, the author specified in the help file)
> 
> 2) Tracking of modifications: any derivatives must keep a record that allows to see how the original work has been modified, either via a changelog, or through publically accessible version control.
> 
> 3) Preservation of the additions: licencing of any derivatives of this work must maintain requirements 1,2.
>

**Comment by florianhartig** [comment]
aeh, I had forgotten about this ... I think this was being overcareful, I'd vote to fall back to GLP3, Maurizio, what are your feelings about this?

**Comment by Rasilgon** [comment]
I agree with Florian. On branch develop I set LICENSE to GLP3. 

I think we should create a CITATION file, so that users can access with

 `citation(package = "rLPJGUESS")`

**Comment by florianhartig** [comment]
Licence is fixed in develop

Citation is created automatically from description, works now
