### ISSUE TITLE
remove rLPJ from the repo page

### ISSUE THREAD

**Issue by Rasilgon** [biometry/RLPJ#45]

**Comment by florianhartig** [comment]
don't understand what this refers to?

**Comment by Rasilgon** [comment]
Replace Rlpj by rLPJGUESS here http://biometry.github.io/rLPJGUESS/

**Comment by florianhartig** [comment]
ah, OK ... this is just the readme.md file, apparently I have overlooked some one old link, the one with the releases - is that what you mean? Changed in https://github.com/biometry/rLPJGUESS/commit/fb97710f8dc250ecf972647db1f1350ad93a56cd

**Comment by Rasilgon** [comment]
yes, great! Then we can close it!
