### ISSUE TITLE
About some question on LPJ model and the package

### ISSUE THREAD

**Issue by Algernonthanks** [biometry/RLPJ#48]
Dear developer, thank you for your great work! Recently, l just started to study LPJ-GUESS model.  l have some question about the package, and l hope you can help me. 
1, l have compiled the LPJ-GUESS and there are some files in the build folder, but l do not which one to use create a link to the guess executable, the guesscmd or guess? l am in the window system. 
2, I'm confused about ‘gridlist.txt’, In this document, we should import the longitude and latitude of the simulated region？ or all the grid size  in the analyzed region?
Finally, l take the liberty of asking for a request: can you share with me the data used in this package test? . l think that can help me understand the model. 
 Thank you for you again!

**Comment by Rasilgon** [comment]
Hi AbelDavid,

below you find the answers to your reported issues. Next time please consider reporting each issue separately, it makes it easier for us to answer and  for everyone else to follow the *issue*.

Issue 1: 

> 1, l have compiled the LPJ-GUESS and there are some files in the build folder, but l do not which one to use create a link to the guess executable, the guesscmd or guess? l am in the window system.

 You should use the name of the executable file you have. In Windows is guesscmd.exe.

Issue 2:
> I'm confused about ‘gridlist.txt’, In this document, we should import the longitude and latitude of the simulated region？ or all the grid size in the analyzed region?

The gridlist.txt is the text file having the coordinates of the grid or the grid IDs. The formatting is given by the model not by the package. You can find an example file in the package by typing:
`mainDir <- system.file("extdata", package = "rLPJGUESS")`
`list.files(mainDir)`
`readLines(file.path(mainDir, "gridlist.txt")) `

This code lines are from the package vignette. You should be able to access it by typing 
`vignette("rLPJGUESS")`
or at this link https://cdn.rawgit.com/biometry/rLPJGUESS/80a8ac8a/rLPJGUESS/vignettes/rLPJGUESS.html

rLPJGUESS is an interface for the model LPJ-GUESS. If you have questions regarding the model, you   might consider contacting the model developers.

**Comment by Algernonthanks** [comment]
Dear Rasilgon, thank  you for your detailed explanation. when l try to run test data in the rLJPGUESS package, l found the test data in the test folder in empty.  l take the liberty of asking for a request: can you share with me the data used in this package test?

**Comment by mauriziobagnara** [comment]
Hi AbelDavid,
I apologize for my late reply.
The test data folder is meant for internal testing only, therefore it does not include forcing or input data.
If you are still interested in trying out the package, have a look at our recent publication on Environmental Modelling and Software "An R package facilitating sensitivity analysis, calibration and forward simulations with the LPJ-GUESS dynamic vegetation model" (https://www.sciencedirect.com/science/article/pii/S1364815217310629). You will find detailed instructions and code to perform several tasks there, as well as the link to the data used in all the simulations.
I hope this helps!

**Comment by florianhartig** [comment]
I think this can be closed, so will close.

**Comment by Luoyk1** [comment]
Hi everyone,

I'm a new user setting up a transient run (1901-2024) and have run into a data format issue after completing my spinup. The transient run fails with this specific error:

Format of input/ndep_1901-2021.bin incompatible with this version of GlobalNitrogenDeposition.h
I'm quite sure this means the .bin file I have is from an older version. I've looked through the source code package for a conversion script but couldn't find one.

Could anyone point me to where I can download a compatible GlobalNitrogenDeposition.bin file for a more recent version of the model? My source code seems to be from around mid-2021.

Any help or advice would be fantastic!

Thanks,
Yongkun Luo
