### ISSUE TITLE
introduce setting argument on runLPJ

### ISSUE THREAD

**Issue by mauriziobagnara** [biometry/RLPJ#5]
Introduce a "settings" argument to include the followings:
plot.data, save.plots, file.co2, file.cru, file.cru.misc,file.ndep, file.temp, file.prec, file.insol,delete,
scale, mode, template1, template2, gridList,processing, parallel .

Add function to visualize all possible settings and default values.

runLPJ should look like this at the end:
runLPJ(setupObject, typeList, parameterList, settings)

In addition: remove mainDir argument and use setupObject$mainDir

**Comment by Rasilgon** [comment]
MainDir and parallel are already removed. 
I created a setupObject class that is recognized by runLPj.

Do you mean to pack all  settings as done for parallel setup(1), creating a specific settings object that be reused,  or as done parameterList(1),  a list with no fix structure?

**Comment by mauriziobagnara** [comment]
Where is parallel now?
I mean something that could be called like this:
`
mySettings<-list("plot.data"=TRUE, "save.plots"=TRUE, "file.co2"="fileCO2.txt", "scale"="europe", "mode"="cf","template1"="europe.ins")

runLPJ(setupObject=mySetup, parameterList=myPars,settings=mySettings)
`
It would require a settings object, possibly a list, always accessible by the user via a callable function (could be called settingsLPJ() ), with some default settings (like plot.data=TRUE) and some that must be user-defined(like the template names). We could take the settings in the BayesianTools package as an example.

**Comment by Rasilgon** [comment]
I implemented the settings. Now runLPJ is called as:

`runLPJ(x = NULL, typeList = NULL, parameterList = NULL, settings = NULL)`

being X either the mainDir or the parallel setup.

**Comment by mauriziobagnara** [comment]
check help files

**Comment by mauriziobagnara** [comment]
I'm getting errors both in parallel and in single run:
in single run:
`Error in read.table(file.path(outDir, paste(typeList.valid[[j]], ".out",  : 
  duplicate 'row.names' are not allowed
In addition: Warning messages:
1: In runLPJWrapper(singleRun) :
  The output type list has not been provided
4: In runLPJWrapper(singleRun) : Setting type list to default values.`

in parallel:
`Calculating model outputs

Reading the parallel object structure
  |====================================================================================================| 100%

Creating a SOCK cluster with 2  cores
Sending tasks to the cores
Error in checkForRemoteErrors(val) : 
  10 nodes produced errors; first error: Please provide a valid run directory.
`

**Comment by mauriziobagnara** [comment]
Need fixed asap, essential to test it during the ongoing spring school.

**Comment by Rasilgon** [comment]
Hi Maurizio, 

I saw you reverted the changes. 
Do you want to keep the older version until the School finish?

**Comment by mauriziobagnara** [comment]
Solved
