### ISSUE TITLE
add default parameter values function

### ISSUE THREAD

**Issue by mauriziobagnara** [biometry/RLPJ#6]
Would be nice/important to have a function that returns parameter names, default values, mode when they are used (global/europe), original names,and so on. The returned object can be structured as a matrix or dataframe.

**Comment by Rasilgon** [comment]
I understand it right what you mean is the getParamaterList function.
It allows to get all parameters for europe/global.
`parameterList <- getParameterList("global")
`
Currently it returns a named list.

```
parameterList$run_lamda_max // parameterList['run_lamda_max']
[1] 0.8
```

Or do you mean the query an specific parameter?

**Comment by mauriziobagnara** [comment]
ok, I forgot about that one.
I would anyway change its output to something more easily readable/subsettable, like a matrix or dataframe. Would be nice to have columns with the full name, the PFT/species, the default value, and perhaps its original name in the .ins files.
