### ISSUE TITLE
LPJ on windows server

### ISSUE THREAD

**Issue by mauriziobagnara** [biometry/RLPJ#8]
Compile LPJ on the windows department server and test Rlpj. 
To get access, ask Holger and let me know if there are any problems. Ideally this should be done within this week/beginning of the next.

**Comment by Rasilgon** [comment]
Could Stefan try it out on his laptop? He has windows and the model already compiled. 
Or do you prefer to have LPJ-GUESS on one windows machine of the department?

**Comment by mauriziobagnara** [comment]
This is for using all available resources for the calibrations to come. If I needed Stefan to try it out, I would have asked him directly. 
Let me know if you can get access or if I need to write Holger.

**Comment by mauriziobagnara** [comment]
Solved
